import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({ 
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Pick the weights you need
  variable: "--font-montserrat", // Define a CSS variable name
});

export const metadata: Metadata = {
  title: "Cashier App",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/Vector.png",       // Cashier logo (PNG)
    shortcut: "/icons/cartIcon.svg", // SVG fallback for quick links
    apple: "/icons/Vector.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
